spring:
  application:
    name: module-goods
  sleuth:
    sampler:
      probability: 1.0 # 将采样比例设置为 1.0，也就是全部都需要。默认是 0.1
  zipkin:
    base-url: http://192.168.153.131:9411 # 指定了 Zipkin 服务器的地址
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/shop?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: root
  kafka:
    bootstrap-servers: 192.168.176.129:9092,192.168.176.129:9093,192.168.176.129:9094
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      group-id: test
      enable-auto-commit: true
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
  #redis:
  #  cache.clusterNodes: 192.168.176.129:6379,192.168.176.130:6379,192.168.176.131:6379
  #  cache.commandTimeout: 5000
server:
  port: 9004
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka/
feign:
  hystrix:
    enabled: true
mybatis:
  mapper-locations: classpath:/mybatis/mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
apollo:
  meta: http://192.168.153.131:8080
  bootstrap:
    enabled: true
    eagerLoad:
      enabled: true


