server:
  port: 9999

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/

spring:
  application:
    name: config-server
  kafka:
    bootstrap-servers: 192.168.153.131:9092，192.168.153.131:9093，192.168.153.131:9094
  cloud:
    config:
      server:
        git:
          uri: https://github.com/powerjiajun/config
          searchPaths: /
    bus:
      refresh:
        enabled: true
management:
  endpoints:
    web:
      exposure:
        include: '*'